import Head from "next/head";
import Hero from "../Components/Hero";
import styled from "styled-components";

const Some = styled.div`
  height: 100vh;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Some />
    </div>
  );
}
